### ISSUE TITLE
MapIcon & MaterialIcon 

### ISSUE THREAD

**Issue by ChrisJohns-me** [0x73/SwiftIconFont#101]
### SwiftIconFont Version
6.1.0

### Steps to Reproduce
1. With SwiftIconFont installed, visit the [Material Design Icons](https://material.io/resources/icons/) library or [Map Icons](http://map-icons.com/) library
1. Copy the name of an icon that contains an underscore (ie. `accessibility_new`)
1. Paste the copied name to use as a code (ie. `UIImage(from:code:textColor:backgroundColor:size:)`
Such as:
```swift
UIImage(from: .materialIcon,
        code: "accessibility_new", // <--
        textColor: .black,
        backgroundColor: .clear,
        size: CGSize(width: 50, height: 50))
```

### Expected behavior
Material Design Icon for `accessibility_new` correctly displays as a UIImage

### Actual Behavior
Runtime failure
`Thread 1: Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value`

### Workaround
When using MaterialIcon or MapIcon, replace any `_` with `.` ie. change from: `accessibility_new` to `accessibility.new`

#### Possible Fix 1
Update README file with "quirks", minor changes needed, or expectations that the user should have when referencing the font's libraries.

#### Possible Fix 2
Update the keys within the array mapping to directly reflect the font's libraries. (`MapIcon.swift` and `MaterialIcon.swift`)

#### Possible Fix 3
Add a nil check to verify that the icon has been found. If not, throw or print a more specific error

#### Related
#37

**Comment by 0x73** [comment]
Thanks. I'm working on it.

**Comment by 0x73** [comment]
Fixed
