### ISSUE TITLE
fontawesome 5 not work

### ISSUE THREAD

**Issue by kaich** [0x73/SwiftIconFont#103]
In the demo, so many icons show "?". There are at least 800 free ICONS. But I didn't see them.

**Comment by 0x73** [comment]
Can you try changing FontAwesome variants from segments?

**Comment by dmitryLagoda** [comment]
I confirm, that FontAwesome icons don't work correctly. Switching variants doesn't help. Here is the screen  from example app.
<img width="484" alt="Screenshot 2020-12-21 at 12 35 57" src="https://user-images.githubusercontent.com/2717056/102767988-18c3d580-4389-11eb-95ae-9f55cc386d91.png">

**Comment by dmitryLagoda** [comment]
@0x73 please, take a look. Not sure, if closed issue sends notifications.
