### ISSUE TITLE
Pod missing ttf files

### ISSUE THREAD

**Issue by walsht** [0x73/SwiftIconFont#2]
The pod only includes the FontAwesome.ttf file.

**Comment by rjvandoesburg** [comment]
I can confirm that by instaling this library via pods it is incomplete.

Not only are the fonts not included, the project files themselves are not the same as the ones provided in the demo, as such the documentation does not conform the Pod.

**Comment by 0x73** [comment]
Yes, pod version is very old. I will update.

**Comment by lunswor** [comment]
Any update on this? Thanks

**Comment by kommaly** [comment]
Please update pod
