### ISSUE TITLE
UIbutton change icon programmatically 

### ISSUE THREAD

**Issue by eliteproxy7** [0x73/SwiftIconFont#20]
how can i programmatically in swift change the icon on an existing button which already has the class.

**Comment by trangsinh87** [comment]
update new title and call parseIcon
`
yourButton.setTitle("io:android-options updated", forState: .Normal)
yourButton.parseIcon()
`

**Comment by kvacquier** [comment]
Not working actually. I've got an  "unknown" icon instead of the one i ask when updating and then parsing it.

**Comment by kvacquier** [comment]
How I solved it : 
```
let title = "io:android-options"
button.setAttributedTitle(nil, for: .normal)
button.titleLabel?.text = title
button.setTitle("\(title)", for: .normal)
button.parseIcon()
```
