### ISSUE TITLE
Based on JQSwiftIcon?

### ISSUE THREAD

**Issue by josejuanqm** [0x73/SwiftIconFont#23]
Hey man, i noticed that you used some of my code and logic on this repository, 

thats cool and all but.. maybe granting some ownership or something would be nice.
simply renaming swift files, refactoring  and changing author doesn't mean its fully yours haha (not cool) anyways, i appreciate the interest on my idea of string interpolation, and i believe that granting some kind of ownership would be nice

Thanks.

**Comment by 0x73** [comment]
Readme updated.

**Comment by josejuanqm** [comment]
Thanks man! :)
