### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by mrugeshtank** [0x73/SwiftIconFont#27]
Please put changelog.md, so others can easily track which version of library supports which version of swift.

**Comment by lvdaqian** [comment]
it seems support swift 3.0 from version 2.6.0, But it never support swift 2.3.

**Comment by rajeshm20** [comment]
why swiftIconFont working on simulator but  not on devices(iphone, ipad) ?

**Comment by rajeshm20** [comment]
pod 'SwiftIconFont', '~> 2.5.6'

**Comment by rajeshm20** [comment]
Swift 2.2
