### ISSUE TITLE
parseIcon works only with FontAwesome

### ISSUE THREAD

**Issue by shshalom** [0x73/SwiftIconFont#28]
Hi,
Love this framework but I seem to have a problem with parseIcon, as it works only with fa:\* 
I tried all other sources but non of them works.

I am working with Xcode 8 running iOS target 9.0, the device it self has iOS 10

Thanks.

**Comment by 0x73** [comment]
Thanks. I'll check this.

**Comment by shshalom** [comment]
Any update on this issue?

**Comment by 0x73** [comment]
Yes, I checked. Can I see the your code?
