### ISSUE TITLE
Problem with Material icon with two or more words 

### ISSUE THREAD

**Issue by Valerija456** [0x73/SwiftIconFont#37]
When i use material icon with one word for  ex:"accessibility", i don't have any problem, but when i try to use icons with two or more words for ex: "flight_land" the icon doesen't appear. Here is an image http://imgur.com/OJ3mO66 and my code in addition 

cellIcon.font = UIFont.icon(from: .MaterialIcon, ofSize: 30.0)
        cellIcon.text = String.fontMaterialIcon(icon.replacingOccurrences(of: "ic_", with: "").replacingOccurrences(of: "_", with: "-"))

**Comment by livenplay** [comment]
Replace underscores "_" with dots "." in material icon title. ex: "flight.land", "filter.center.focus" etc
