### ISSUE TITLE
Use of undeclared type 'SwiftIconButton'

### ISSUE THREAD

**Issue by clbemre** [0x73/SwiftIconFont#40]
'weak' may only be applied to class and class-bound protocol types, not '<<error type>>'

help me please .

**Comment by 0x73** [comment]
Can I see your code and podfile ?

**Comment by clbemre** [comment]
# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'MyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SideMenu'
	pod 'Alamofire', '~> 4.0'
    # pod 'SwiftyJSON', git: 'https://github.com/BaiduHiDeviOS/SwiftyJSON.git', branch: 'swift3'
    pod 'SwiftyJSON'
    pod 'SwiftIconFont'
    pod 'MaterialKit', :git => 'https://github.com/faresbh/MaterialKit', :branch => "swift3"
  # Pods for AkfedAracKiralama

  target 'MyApp' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Myapp' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end


Label içinde kullanınca problem yok iconları gösterebiliyorum, ancak direk component olarak kullandığım zaman (button vs) aynı hatayı veriyor.
