### ISSUE TITLE
can you support Tabbar

### ISSUE THREAD

**Issue by pprevalon** [0x73/SwiftIconFont#51]
although I'm able to get the image on the tabbar i have issues when selected to change the image.

**Comment by rocwangv** [comment]
I also have questions about **Tabbar** usage , how can I use `SwiftBarButtonItem` instead of `UITabBarItem`  ?
Thanks!

**Comment by 0x73** [comment]
I'm working on this issue.

**Comment by 0x73** [comment]
SwiftIconFonts support UITTabbar selected image!
Please check Example project or  0x73@295c07f648867fa0f0652ba28e65763169f0ee6b

```swift
@IBInspectable var SelectedIcon: String?
@IBInspectable var SelectedIconFontSize: CGFloat = 20.0
@IBInspectable var SelectedIconImageSize: CGSize = CGSize(width: 20, height: 20)
@IBInspectable var SelectedIconColor: UIColor = UIColor.black```
