### ISSUE TITLE
Suggest to change the version number `2.7.2`

### ISSUE THREAD

**Issue by allenhuang** [0x73/SwiftIconFont#70]
I did a `pod update` recently and found build error in project due to SwiftIconFont.
After some debugging, I found SwiftIconFont updated from `2.7.1` to `2.7.2`

The version `2.7.2` have migrated to support Swift 4.0.  But I still use Swift 3.2 to compile and got the errors.
It seems not a minor change. So I suggest to use a major version number to tag it.

It will be good to have a note on README too.

Thanks for your effort to maintain this lib.

**Comment by 0x73** [comment]
Thanks for your attention. 👍
