### ISSUE TITLE
Font Awesome 5

### ISSUE THREAD

**Issue by h36ahmed** [0x73/SwiftIconFont#72]
Hey buddy, would you be able to add Font Awesome 5 Icons? :)

**Comment by 0x73** [comment]
I'm working on this. Please see [https://github.com/0x73/SwiftIconFont/tree/fa5](/_user_/_project_/tree/_branch_)

**Comment by h36ahmed** [comment]
Hey buddy, wondering when will this be implemented? :)

**Comment by 0x73** [comment]
@h36ahmed done!
