### ISSUE TITLE
Carthage install hang

### ISSUE THREAD

**Issue by purkylin** [0x73/SwiftIconFont#97]
version: 3.0.0
carthage version: 0.33.0

**Comment by KoichiroKAMADA** [comment]
Yes. It takes horrible long time :/

**Comment by purkylin** [comment]
Maybe  carthage bug

**Comment by jeanfw** [comment]
same on 4.0.0 / carthage 0.33.0

did anyone find a workaround / fix ?

**Comment by 0x73** [comment]
fixed
